### ISSUE TITLE
Hydro fails with django 1.9

### ISSUE THREAD

**Issue by technomosh** [Convertro/Hydro#6]
If django <=1.8.x is already installed, then Hydro is working fine. If django is not installed, installing it is pulling the latest (since `requirements.txt` specifies `Django>=1.5.1`) which fails with `ImportError: cannot import name get_cache` since `in_memory.py` relies on `from django.core.cache import get_cache`.

**Comment by gcko** [comment]
Should we fix it to work with 1.9, then in the future switch the version specifier to something like, `Django ~= 1.9`?

https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file

**Comment by technomosh** [comment]
Yes @gcko . The quick and dirty solution would be to fix it for 1.9 with something like:
`if django.VERSION[:2] < (1, 9): from django.core.cache import CacheHandler, caches ...` and use the 1.9 relevant method otherwise.
For the long run: I'm thinking about getting rid of the django dependency altogether. This will involve changing two parts in the Hydro code base:

1. The in-memory and mysql cache wrappers. For in-memory it should be a simple dictionary. For mysql we should probably implement it on our own (I suspect you already know something similar from CVO).
2. The query templates should rely on jinja instead of django as it is lightweight and gained huge popularity for that exact purpose.

Finally, I suspect that whomever is using Hydro is also potentially using Django, and I don't want to chase dependency conflicts.

**Comment by technomosh** [comment]
Handling this issue in [PR 7](https://github.com/Convertro/Hydro/pull/7).
It is handled without removing the Django dependency entirely. I hope that future versions will take care of that.

**Comment by technomosh** [comment]
The fix will be released as part of Hydro 0.1.7.
